[package]
name = "world-id-bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
tokio = { version = "1", features = ["full"] }
tracing = { version = "0.1", features = ["log"] }
tower = { version = "0.4.13", features = ["make"] }
hyper = { version = "0.14.26", features = ["http1", "server", "tcp"] }
redis = { version = "0.23.0", features = ["tokio-comp", "connection-manager"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt"] }
