[package]
license = "MIT"
edition = "2021"
version = "0.1.0"
name = "world-id-bridge"
authors = ["Miguel Piedrafita <rust@miguel.build>"]
repository = "https://github.com/worldcoin/wallet-bridge"
description = "A bridge between the World ID SDK and the World App"

[dependencies]
axum = "0.6.20"
tower = "0.4.13"
serde = "1.0.183"
dotenvy = "0.15.7"
lambda_http = "0.8.1"
axum-aws-lambda = "0.5.0"
tracing = { version = "0.1", features = ["log"] }
tokio = { version = "1.31.0", features = ["full"] }
tower-http = { version = "0.4.3", features = ["cors"] }
redis = { version = "0.23.0", features = ["tokio-comp", "connection-manager"] }
tracing-subscriber = { version = "0.3", default-features = false, features = [
    "fmt",
] }

[build-dependencies]
chrono = "0.4.26"
